### PR TITLE
v1.2, .NET core and .NET framework NuGet package

### PR DESCRIPTION
**Pull request by jchristn**
Consolidated both .NET Core and .NET Framework into a single project (```Geolocation```).  Had to up-rev to .NET Core 2.0 and .NET Framework 4.5.1.  There's a warning in your unit tests about a deprecated method, but otherwise, this should do the trick.

The ```bin/release``` directory contains a NuGet package for v1.2.  I also added missing XML documentation.

Cheers,
Joel

### CODE REVIEW

**Comment by scottschluer** [comment]
@jchristn I just merged a smaller change ahead of this which may have resulted in a couple of easy-to-fix conflicts. Would you mind pushing the resolved branch up and I'll get this merged? Thanks!

**Comment by jchristn** [comment]
Hi @scottschluer I resolved two of the three conflicts.  The conflict in the solution file removes the Geolocation project from the solution altogether (which I believe is unintended).  Commit is here: https://github.com/jchristn/geolocation/commit/98bd2e61f9c975d76f7744b70115a48f6f10932b

**Comment by jchristn** [comment]
Here is the change in question, as you can see it pulls Geolocation out of the solution.
```
<<<<<<< v1.2
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Geolocation", "Geolocation\Geolocation.csproj", "{01211022-EEDA-43C8-9A9B-2B2A6A42E073}"
=======
>>>>>>> master
```

**Comment by jchristn** [comment]
@scottschluer how would you like to proceed?  If easier I can just publish it to NuGet and attribute back to your URL/name/copyright.

**Comment by jchristn** [comment]
Hi @scottschluer - friendly reminder on this one.  Happy to just post it on your behalf, but I'm sure you'd like the NuGet downloads attributed to you rather than me :)

**Comment by scottschluer** [comment]
Hey @jchristn, sorry for the slow response. Still has conflicts that need to be resolved in the solution file. If you can fix that up, I'll get it merged ASAP. Thanks!

**Comment by wilka** [comment]
@jchristn I noticed there are some files added to the repo from the `.vs` folder (e.g. `.vs/Geolocation/config/applicationhost.config`) The files in that folder are usually machine specific things (and it looks like that folder is already excluded from git via the `.gitignore. file), so you might want to remove those files from this Pull Request to avoid other people getting your versions of those files when they checkout the latest code.

**Pull request merged**
